### PR TITLE
Implement the VerifyPayment function. 

### PR DESCRIPTION
**Pull request by DNNMonster**
Mods to implement the VerifyPayment function. Minor code formatting.  Remove & sort unused usings.

### CODE REVIEW

**Comment by leedavi** [comment]
Have you tested this against the paypal sandbox?  Does it work?

**Comment by DNNMonster** [comment]
Yes 
pp_payment

**Comment by DNNMonster** [comment]
pp_payment2

**Comment by leedavi** [comment]
OK, Great thx for all your help!

**Pull request merged**
